# Generated by Django 3.2.7 on 2021-10-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.CharField(default='50', max_length=10),
        ),
    ]
